
services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.4
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xmx512m -Xms512m  # 👈 Reduce memory usage to 512MB
    depends_on:
      - zookeeper

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  user_service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - postgres
    env_file:
      - ./user_service/.env

  media_service:
    build:
      context: .
      dockerfile: media_service/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - kafka
      - postgres
    env_file:
      - ./media_service/.env

  feed_service:
    build:
      context: .
      dockerfile: feed_service/Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - kafka
      - postgres
    entrypoint: ["sh", "-c", "sleep 15 && uvicorn app.main:app --host 0.0.0.0 --port 8002"]
    env_file:
      - ./feed_service/.env

volumes:
  pgdata:
